version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-server-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_local_mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-local
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
  php:
    image: php:8.2-fpm
    container_name: php-server-local
    restart: always
    volumes:
      - ./../app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    container_name: nginx-local
    restart: always
    ports:
      - "81:81"
    volumes:
      - ./../app:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
volumes:
  mysql-data:
